# fly.toml file generated for termify on 2023-04-05T21:17:14-05:00

app = "termify"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "bos"

[build]
  builder = "heroku/buildpacks:20"
  [args]
    NODE_VERSION=18

[env]
  PORT = "8080"
  PRIMARY_REGION = "bos"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
